version: '3'

services:
  api:
    build: .
    ports:
      -"5000:8080"
    volumes:
      -./data:/app/data
      -./models:/app/models
      -./reports:/app/
    environment:
      - FLASK_ENV=development
      - PORTS=8080

  frontend:
    image: nginx:alpine
    ports:
      -"8080:80"
    volumes:
      -./src/frontend:/usr/share/nginx/html
    depends_on:
      - api